export PYTHONWARNINGS="ignore:DEPRECATION"

source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/zshrc"

source "${ZDOTDIR:-$HOME}/.zprezto/custom/load.zsh"

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
